settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: learn-thudep22-cn # unique identifier
    name: learn.thudep22.cn
    description: '工物系学习仓库' # default=empty
    url: 'https://learn.thudep22.cn/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: game-thudep22-cn
    name: game.thudep22.cn
    url: 'https://game.thudep22.cn/'
    method: GET
    expectStatus: 200
    followRedirect: false
    linkable: false

  - id: csset-doc-thudep22-cn
    name: csset-doc.thudep22.cn
    \description: 'CSSET开发文档'
    url: 'https://csset-doc.thudep22.cn/'
    method: GET
    expectStatus: 200
    followRedirect: false
    linkable: false
